# Generated by Django 3.2.9 on 2022-10-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genretype', models.CharField(max_length=101, verbose_name='Género do livro')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.books')),
            ],
        ),
    ]
