# Generated by Django 3.2.9 on 2022-10-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorname', models.CharField(max_length=101, verbose_name='Nome de Editora')),
                ('edited', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.books')),
            ],
        ),
    ]
